# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 466)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 171, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mainMenulayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mainMenulayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.mainMenulayout.setContentsMargins(5, 0, 5, 0)
        self.mainMenulayout.setSpacing(0)
        self.mainMenulayout.setObjectName("mainMenulayout")
        self.addProduct_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addProduct_button.setObjectName("addProduct_button")
        self.mainMenulayout.addWidget(self.addProduct_button)
        self.issueProduct_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.issueProduct_button.setObjectName("issueProduct_button")
        self.mainMenulayout.addWidget(self.issueProduct_button)
        self.history_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.history_button.setObjectName("history_button")
        self.mainMenulayout.addWidget(self.history_button)
        self.categories_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.categories_button.setObjectName("categories_button")
        self.mainMenulayout.addWidget(self.categories_button)
        self.map_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.map_button.setObjectName("map_button")
        self.mainMenulayout.addWidget(self.map_button)
        self.settings_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.settings_button.setObjectName("settings_button")
        self.mainMenulayout.addWidget(self.settings_button)
        self.exit_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.exit_button.setObjectName("exit_button")
        self.mainMenulayout.addWidget(self.exit_button)
        self.mainMenuLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainMenuLabel.setGeometry(QtCore.QRect(0, 0, 161, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainMenuLabel.sizePolicy().hasHeightForWidth())
        self.mainMenuLabel.setSizePolicy(sizePolicy)
        self.mainMenuLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mainMenuLabel.setObjectName("mainMenuLabel")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(610, 40, 121, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.ProductInfo_layuot = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.ProductInfo_layuot.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.ProductInfo_layuot.setContentsMargins(0, 0, 0, 0)
        self.ProductInfo_layuot.setSpacing(0)
        self.ProductInfo_layuot.setObjectName("ProductInfo_layuot")
        self.productName_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productName_label.sizePolicy().hasHeightForWidth())
        self.productName_label.setSizePolicy(sizePolicy)
        self.productName_label.setMaximumSize(QtCore.QSize(16777215, 60))
        self.productName_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.productName_label.setBaseSize(QtCore.QSize(0, 0))
        self.productName_label.setObjectName("productName_label")
        self.ProductInfo_layuot.addWidget(self.productName_label)
        self.productDescription_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productDescription_label.sizePolicy().hasHeightForWidth())
        self.productDescription_label.setSizePolicy(sizePolicy)
        self.productDescription_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.productDescription_label.setObjectName("productDescription_label")
        self.ProductInfo_layuot.addWidget(self.productDescription_label)
        self.productUnit_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productUnit_label.sizePolicy().hasHeightForWidth())
        self.productUnit_label.setSizePolicy(sizePolicy)
        self.productUnit_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.productUnit_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.productUnit_label.setObjectName("productUnit_label")
        self.ProductInfo_layuot.addWidget(self.productUnit_label)
        self.productCount_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productCount_label.sizePolicy().hasHeightForWidth())
        self.productCount_label.setSizePolicy(sizePolicy)
        self.productCount_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.productCount_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.productCount_label.setObjectName("productCount_label")
        self.ProductInfo_layuot.addWidget(self.productCount_label)
        self.productPlace_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productPlace_label.sizePolicy().hasHeightForWidth())
        self.productPlace_label.setSizePolicy(sizePolicy)
        self.productPlace_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.productPlace_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.productPlace_label.setObjectName("productPlace_label")
        self.ProductInfo_layuot.addWidget(self.productPlace_label)
        self.productShipper_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productShipper_label.sizePolicy().hasHeightForWidth())
        self.productShipper_label.setSizePolicy(sizePolicy)
        self.productShipper_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.productShipper_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.productShipper_label.setObjectName("productShipper_label")
        self.ProductInfo_layuot.addWidget(self.productShipper_label)
        self.productSertificate_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productSertificate_label.sizePolicy().hasHeightForWidth())
        self.productSertificate_label.setSizePolicy(sizePolicy)
        self.productSertificate_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.productSertificate_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.productSertificate_label.setObjectName("productSertificate_label")
        self.ProductInfo_layuot.addWidget(self.productSertificate_label)
        self.Search_line = QtWidgets.QLineEdit(self.centralwidget)
        self.Search_line.setGeometry(QtCore.QRect(180, 10, 341, 20))
        self.Search_line.setObjectName("Search_line")
        self.Search_button = QtWidgets.QPushButton(self.centralwidget)
        self.Search_button.setGeometry(QtCore.QRect(530, 10, 71, 20))
        self.Search_button.setObjectName("Search_button")
        self.productInfo_label = QtWidgets.QLabel(self.centralwidget)
        self.productInfo_label.setGeometry(QtCore.QRect(610, 10, 121, 16))
        self.productInfo_label.setObjectName("productInfo_label")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(180, 40, 421, 401))
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setVisible(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.model = QtGui.QStandardItemModel(parent=self.tableView)
        self.model.setHorizontalHeaderLabels(['Name', 'Sertificate', 'Count', 'Unit', 'Place'])
        self.tableView.setModel(self.model)
        self.tableView.setColumnWidth(0, 140)
        self.tableView.setColumnWidth(1, 60)
        self.tableView.setColumnWidth(2, 60)
        self.tableView.setColumnWidth(3, 80)
        self.tableView.setColumnWidth(4, 81)
        self.tableView.setAutoScroll(True)
        self.tableView.setEditTriggers(QtWidgets.QTableView.NoEditTriggers)
        self.tableView.setSelectionMode(QtWidgets.QTableView.SingleSelection)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addProduct_button.setText(_translate("MainWindow", "Add product"))
        self.issueProduct_button.setText(_translate("MainWindow", "Issue product"))
        self.history_button.setText(_translate("MainWindow", "Watch history"))
        self.categories_button.setText(_translate("MainWindow", "Categories"))
        self.map_button.setText(_translate("MainWindow", "Map"))
        self.settings_button.setText(_translate("MainWindow", "Settings"))
        self.exit_button.setText(_translate("MainWindow", "Logout and Exit"))
        self.mainMenuLabel.setText(_translate("MainWindow", "MAIN MENU"))
        self.productName_label.setText(_translate("MainWindow", "Product Name"))
        self.productDescription_label.setText(_translate("MainWindow", "(description)"))
        self.productUnit_label.setText(_translate("MainWindow", "unit"))
        self.productCount_label.setText(_translate("MainWindow", "(count)"))
        self.productPlace_label.setText(_translate("MainWindow", "place"))
        self.productShipper_label.setText(_translate("MainWindow", "shipper"))
        self.productSertificate_label.setText(_translate("MainWindow", "sertificate"))
        self.Search_button.setText(_translate("MainWindow", "Search"))
        self.productInfo_label.setText(_translate("MainWindow", "Product Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

